import type { FC, ReactElement } from 'react'

import Head from 'next/head'

import Header from '@components/header/header'
import Footer from '@components/footer/footer'
import Loader from '@common/loader/loader'

const Layout: FC<{ children: ReactElement }> = ({ children }) => {
	return (
		<>
			<Head>
				<title>iZZi RIDE</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Loader />
			
			<Header />
			<main>{children}</main>
			<Footer />
		</>
	)
}

export default Layout
