import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'

import Header from '@components/header/header'
import Footer from '@components/footer/footer'

const clashDisplayFont = localFont({
    src: [
        {
            path: '../../public/fonts/ClashDisplay/ClashDisplay-Extralight.woff2',
            weight: '100',
            style: 'normal',
        },
        {
            path: '../../public/fonts/ClashDisplay/ClashDisplay-Light.woff2',
            weight: '300',
            style: 'normal',
        },
        {
            path: '../../public/fonts/ClashDisplay/ClashDisplay-Regular.woff2',
            weight: '400',
            style: 'normal',
        },
        {
            path: '../../public/fonts/ClashDisplay/ClashDisplay-Medium.woff2',
            weight: '500',
            style: 'normal',
        },
        {
            path: '../../public/fonts/ClashDisplay/ClashDisplay-Semibold.woff2',
            weight: '600',
            style: 'normal',
        },
        {
            path: '../../public/fonts/ClashDisplay/ClashDisplay-Bold.woff2',
            weight: '700',
            style: 'normal',
        },
    ],
})

export const metadata: Metadata = {
    title: 'iZZi RIDE',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='en'>
            <body className={clashDisplayFont.className}>
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    )
}
